steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/y-test-import-csv/node-repo/node-server:v0.0.9'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/y-test-import-csv/node-repo/node-server:v0.0.9'
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export CLOUDSDK_COMPUTE_REGION=us-central1
        export CLOUDSDK_CONTAINER_CLUSTER=node-dev
        gcloud container clusters get-credentials node-dev --region=us-central1
        kubectl apply -f deployment.yaml
options:
  logging: CLOUD_LOGGING_ONLY